---
# caddy â€” handlers

- name: Restart caddy stack
  community.docker.docker_compose_v2:
    project_src: "/opt/{{ project_name }}"
    files:
      - docker-compose-infra.yml
    services:
      - caddy
    state: restarted
  become: true
