---
# diun â€” handlers

- name: Restart diun stack
  community.docker.docker_compose_v2:
    project_src: "/opt/{{ project_name }}"
    files:
      - docker-compose.yml
    services:
      - diun
    state: restarted
  become: true
