---
# mission-control â€” handlers

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

# I2 fix : utilise mc_service_name au lieu du nom hardcode
- name: Restart mission-control
  ansible.builtin.systemd:
    name: "{{ mc_service_name }}"
    state: restarted
  become: true
  listen: "Restart {{ mc_service_name }}"
