---
# redis â€” handlers

- name: Restart redis stack
  community.docker.docker_compose_v2:
    project_src: "/opt/{{ project_name }}"
    files:
      - docker-compose-infra.yml
    services:
      - redis
    state: restarted
  become: true
