---
galaxy_info:
  role_name: vpn_dns
  author: "{{ project_name }}"
  description: Deploy Headscale extra DNS records for VPN admin access
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Debian
      versions:
        - bookworm
        - trixie
